select * from album;
select * from artist;
select * from customer;
select * from employee;
select * from genre;
select * from invoice;
select * from invoice_line;
select * from media_type;
SELECT * FROM PLAYLIST;
SELECT * FROM PLAYLIST_TRACK;
SELECT * FROM TRACK;

-- EASY TYPE QUESTION

-- Q1 Who is the senior most employee based on job title?

SELECT
	*
FROM
	EMPLOYEE;

SELECT
	*
FROM
	EMPLOYEE
ORDER BY
	LEVELS DESC
LIMIT
	1;
-- Q2 Which country has the most invoices?

SELECT
	*
FROM
	INVOICE;

SELECT
	BILLING_COUNTRY,
	COUNT(*)
FROM
	INVOICE
GROUP BY
	BILLING_COUNTRY
ORDER BY
	2 DESC
LIMIT
	1;
-- Q3 What are top 3 values of total invoice?

SELECT
	*
FROM
	INVOICE;

SELECT
	ROUND(TOTAL::NUMERIC, 2)
FROM
	INVOICE
ORDER BY
	TOTAL DESC
LIMIT
	3;

-- Q4 Which city has the best customers? We would like to throw a promotional 
-- Music festival in the city we made the most money. Write a query that
-- returns one city that has the highest sum of invoice totals. Return both
-- city name & sum of all invoice totals


SELECT
	*
FROM
	CUSTOMER;

SELECT
	*
FROM
	INVOICE;

SELECT
	BILLING_CITY,
	SUM(TOTAL) AS INVOICE_TOTAL
FROM
	INVOICE
GROUP BY
	BILLING_CITY
ORDER BY
	INVOICE_TOTAL DESC;

-- Q5 WHO IS THE BEST CUSTOMER? THE CUSTOMER WHO HAS SPENT THE 
-- MOST MONEY WILL BE DECLARED THE BEST CUSTOMER. WRITE A QUERY
-- THAT RETURNS THE PERSON WHO HAS SPENT THE MOST MONEY

SELECT
	*
FROM
	CUSTOMER;

SELECT
	*
FROM
	INVOICE;

SELECT
	VERSION();

SELECT
	C.FIRST_NAME || C.LAST_NAME AS FULL_NAME,
	ROUND(SUM(I.TOTAL::NUMERIC), 2)
FROM
	CUSTOMER AS C
	JOIN INVOICE AS I ON I.CUSTOMER_ID = C.CUSTOMER_ID
GROUP BY
	1
ORDER BY
	2 DESC
LIMIT
	1;


-- MODERATE LEVEL QUESTION

-- Q6 WRITE QUERY TO RETURN THE EMAIL, FIRST_NAME, LAST_NAME & GENRE OF ALL 
-- ROCK MUSIC LISTENERS. RETURN YOUR LIST ORDERED ALPHABETICALLY BY EMAIL 
-- STARTING WITH A.

SELECT
	*
FROM
	CUSTOMER;

SELECT
	*
FROM
	GENRE;

SELECT
	*
SELECT
	EMAIL,
	FIRST_NAME,
	LAST_NAME,
	G.NAME
FROM
	CUSTOMER AS C
	JOIN INVOICE AS I ON I.CUSTOMER_ID = C.CUSTOMER_ID
	JOIN INVOICE_LINE AS IL ON IL.INVOICE_ID = I.INVOICE_ID
	JOIN TRACK AS T ON T.TRACK_ID = IL.TRACK_ID
	JOIN GENRE AS G ON G.GENRE_ID = T.GENRE_ID
WHERE
	G.NAME LIKE 'Rock'
ORDER BY
	EMAIL ASC;
-- Q7 LET'S INVITE THE ARTIST WHO HAVE WRITTEN THE MOST ROCK MUSIC
-- IN OUR DATASET, WRITE A QUERY THAT RETURNS THE ARTIST NAME AND TOTAL 
-- TRACK COUNT OF THE TOP 10 ROCK BANDS.

SELECT
	*
FROM
	ARTIST;

SELECT
	*
FROM
	ALBUM;

SELECT
	*
FROM
	TRACK;

SELECT
	*
FROM
	GENRE;

SELECT
	AR.ARTIST_ID,
	AR.NAME,
	COUNT(AR.ARTIST_ID) AS NO_OF_SONGS
FROM
	ARTIST AS AR
	JOIN ALBUM AS AL ON AL.ARTIST_ID = AR.ARTIST_ID
	JOIN TRACK AS T ON T.ALBUM_ID = AL.ALBUM_ID
	JOIN GENRE AS G ON G.GENRE_ID = T.GENRE_ID
WHERE
	G.NAME ILIKE 'ROCK'
GROUP BY
	1,
	2
ORDER BY
	3 DESC
LIMIT
	10;


-- Q8 RETURN ALL THE TRACK NAMES THAT HAVE A SONG LENGTH LONGER 
-- THAN THE AVG SONG LENGTH. RETURN THE NAME AND MILLISECONDS FOR EACH 
-- TRACK. ORDER BY THE SONG LENGTH WITH THE LONGEST SONGS LISTED FIRST

SELECT * FROM TRACK;

SELECT NAME, MILLISECONDS
FROM TRACK
WHERE MILLISECONDS > (
	SELECT AVG(MILLISECONDS) AS AVG_TRACK_LENGTH
	FROM TRACK)
ORDER BY MILLISECONDS DESC;
)


-- ADVANCE LEVEL QUESTION

-- Q9 FIND HOW MUCH AMOUNT SPENT BY EACH CUSTOMER ON ARTISTS? WRITE 
-- A QUERY TO RETURN CUSTOMER NAME, ARTIST NAME AND TOTAL SPENT



WITH BEST_SELLING_ARTIST AS(
	SELECT ARTIST.ARTIST_ID AS ARTIST_ID,
		ARTIST.NAME AS ARTIST_NAME,
		SUM(INVOICE_LINE.UNIT_PRICE*INVOICE_LINE.QUANTITY) AS TOTAL_SPENT
	FROM INVOICE_LINE 
	JOIN TRACK ON TRACK.TRACK_ID = INVOICE_LINE.TRACK_ID
	JOIN ALBUM ON ALBUM.ALBUM_ID = TRACK.ALBUM_ID
	JOIN ARTIST ON ARTIST.ARTIST_ID = ALBUM.ARTIST_ID
	GROUP BY 1
	ORDER BY 3 DESC
	LIMIT 1
)
SELECT C.CUSTOMER_ID, C.FIRST_NAME, C.LAST_NAME, BSA.ARTIST_NAME, SUM(IL.UNIT_PRICE*IL.QUANTITY) AS AMOUNT_SPENT
FROM INVOICE I
JOIN CUSTOMER C ON C.CUSTOMER_ID = I.CUSTOMER_ID
JOIN INVOICE_LINE IL ON IL.INVOICE_ID = I.INVOICE_ID
JOIN TRACK T ON T.TRACK_ID = IL.TRACK_ID
JOIN ALBUM AL ON AL.ALBUM_ID = T.ALBUM_ID
JOIN BEST_SELLING_ARTIST AS BSA ON BSA.ARTIST_ID = AL.ARTIST_ID
GROUP BY 1,2,3,4
ORDER BY 5 DESC;

-- Q10 WE WANT TO FIND OUT THE MOST POPULAR MUSIC GENRE FOR EACH 
-- COUNTRY. WE DETERMINE THE MOST POPULAR GENRE AS  THE GENRE WITH 
-- THE HIGHEST AMOUNT OF PURCHASES. WRITE A QUERY THAT RETURNS EACH
-- COUNTRY ALING WITH THE TOP GENRE. FOR COUNTRIES WHERE THE MAXIMUM 
-- NUMBER OF PURCHASES US SHARED RETURN ALL GENRES

WITH POPULAR_GENRE AS (
    SELECT 
        COUNT(INVOICE_LINE.QUANTITY) AS PURCHASES,
        CUSTOMER.COUNTRY, 
        GENRE.NAME,
        GENRE.GENRE_ID,
        ROW_NUMBER() OVER(
            PARTITION BY CUSTOMER.COUNTRY 
            ORDER BY COUNT(INVOICE_LINE.QUANTITY) DESC
        ) AS ROWNB
    FROM INVOICE_LINE
    JOIN INVOICE ON INVOICE_LINE.INVOICE_ID = INVOICE.INVOICE_ID
    JOIN CUSTOMER ON CUSTOMER.CUSTOMER_ID = INVOICE.CUSTOMER_ID
    JOIN TRACK ON TRACK.TRACK_ID = INVOICE_LINE.TRACK_ID
    JOIN GENRE ON GENRE.GENRE_ID = TRACK.GENRE_ID
    GROUP BY CUSTOMER.COUNTRY, GENRE.NAME, GENRE.GENRE_ID
    ORDER BY CUSTOMER.COUNTRY ASC, PURCHASES DESC
)
SELECT * 
FROM POPULAR_GENRE
WHERE ROWNB <= 1;


-- Q10 WRITE A QUERY THAT DETERMINES THE CUSTOMER THAT HAS SPENT THE
-- MOST ON MUSIC FOR EACH COUNTRY. WRITE A QUERY THAT RETURNS THAT 
-- COUNTRY ALONG WITH THE TOP CUSTOMER AND HOW MUCH THEY SPENT. FOR 
-- COUNTRIES WHERE THE TOP AMOUNT SPENT IS SHARED, PROVIDE ALL CUSTOMERS
-- WHO SPENT THIS AMOUNT


WITH
	CUSTOMER_WITH_COUNTRY AS (
		SELECT
			CUSTOMER.CUSTOMER_ID,
			FIRST_NAME,
			LAST_NAME,
			BILLING_COUNTRY,
			SUM(TOTAL) AS TOTAL_SPENDING,
			ROW_NUMBER() OVER (
				PARTITION BY
					BILLING_COUNTRY
				ORDER BY
					SUM(TOTAL) DESC
			) AS ROWNB
		FROM
			INVOICE
			JOIN CUSTOMER ON CUSTOMER.CUSTOMER_ID = INVOICE.CUSTOMER_ID
		GROUP BY
			1,
			2,
			3,
			4
		ORDER BY
			4 ASC,
			5 DESC
	)
SELECT
	*
FROM
	CUSTOMER_WITH_COUNTRY
WHERE
	ROWNB <= 1